classbook/class/urls.py
from django.urls import path
from . import views

app_name = "class"
 
urlpatterns = [
    path('projects/', views.all_projects, name='all-projects'),
    path('project_search_view/', views.project_search_view, name='project_search_view'),
    path('project/<int:pk>', views.single_project, name='current-project'),
    path("remove_like/<int:pk>", views.remove_like, name="remove-like"),
    path("add_like/<int:pk>", views.add_like, name="like-project"),
    path("all-project-comments/<int:pk>", views.all_Comments_of_Project, name="all-project-comments"),
    path("add-comment/<int:pk>", views.add_Comment, name="add-comment"),
    path("edit-comment/<int:pk>", views.edit_Comment, name="edit-comment"),
    path("delete-comment/<int:pk>", views.delete_Comment, name="delete-comment"),
    path('submissions/', views.get_Subissions, name='submissions'),
    path('submit-quiz/<int:pk>/', views.submit_Quiz, name='submit-quiz'),
]

classbook/classbook/urls.py
from django.contrib import admin
from django.urls import path, include

# ovo nam treba za image url-treba pristup do settings da 
# povezemo (settings.MEDIA_URL, i settings.MEDIA_ROOT sa static()
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mysite.urls")),
    path('staff/', include('staff.urls')),
    path('class/', include('class.urls')),
]

# pip install Pillow za slike
# url za images madia, koristimo static()  helping method
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classbook/staff/urls.py
from django.urls import path
from . import views

app_name = "staff"
urlpatterns = [
    path('projects/', views.projects, name='projects'),
    path('create-project/', views.createProject, name='create-project'),
    path('get-project/<int:pk>/', views.getProject, name='get-project'),
    path('delete-project/', views.delete_Project, name='delete-project'),
    path('publish-unpublish-project/<int:pk>/', views.publish_unpublish_Project, name='publish-unpublish-project'),
    path('get-projectNames/', views.get_projectNames, name='get-projectNames'),
    path('update-project-field/<int:pk>/', views.update_ProjectField, name='update-project-field'),
    path('update-pdf-file/<int:pk>/', views.update_pdf_file, name='update-pdf-file'),
    path('delete-file/', views.delete_File, name='delete-file'),
    path('get-create-quiz-question/<int:pk>/', views.get_create_Quiz_Question, name='get-create-quiz-question'),
    path('create-add-question/<int:pk>/', views.create_add_Question, name='create-add-question'),
    path('edit-question/<int:pk1>/<int:pk2>/<int:pk3>/', views.edit_Question, name='edit-question'),
    path('delete-question/<int:pk1>/<int:pk2>/', views.delete_Question, name='delete-question'),
    path('publish-unpublish-quiz/<int:pk>/', views.publish_unpublish_Quiz, name='publish-unpublish-quiz'),
]

classbook/staff/models.py
from embed_video.fields import EmbedVideoField
from django.db import models
from mysite.models import User
 

 
 
# Create your models here.
class Project(models.Model):    
    projectName = models.CharField(max_length=100) 
    description = models.TextField(null=True, blank=True, 
                                   max_length=500)
    # pointing to the User model : to=settings.AUTH_USER_MODEL
    owner = models.ForeignKey(User, on_delete=models.CASCADE, 
                              related_name="author")
    created  = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    num_of_likes = models.IntegerField(default = 0)
    num_of_qustions = models.IntegerField(default = 0)
    # polje koje mora biti kopirano sa Youtub kanala
    video = EmbedVideoField(null=True)  # same like models.URLField()
    pdf = models.FileField(null=True, blank=True)
    project_published = models.BooleanField(default=False)
    id = models.IntegerField(unique=True,
                          primary_key=True,editable=False)
    quiz_published =  models.BooleanField(default=False)

 
    # pointing to the User model:
    # https://docs.djangoproject.com/en/3.2/topics/auth/customizing/#referencing-the-user-model

    #koristimo property decorator za pdfURL()
    # imamo pristup do ove metode kao do property
    # ako nema defoult   vrati prazan string
    @property
    def pdfURL(self):
        try:
            img  = self.pdf.url
        except:
             img = ''
        return img
        
    def __str__(self):
        return f"{self.projectName} has: num_of_likes {self.num_of_likes}, num_of_qustions: {self.num_of_qustions}, project_published:{self.project_published}, quiz_published: {self.quiz_published}"
    
class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_like")
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="project_like")

    def __str__(self):
        return f"{self.user} liked {self.project}"

class Question(models.Model):
    #vrati broj kao string 
    question_quiz = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="quiz_question")    
    id = models.IntegerField(unique=True,primary_key=True,editable=False)
    question = models.CharField(max_length=150)
    answer = models.CharField(max_length=150)
    option_1 = models.CharField(max_length=150)
    option_2 = models.CharField(max_length=150)
    option_3 = models.CharField(max_length=150)


    def __str__(self):
        return f"id: {self.id}\n, projectName: {self.question_quiz.projectName}\n, question: {self.question}\n, answer: {self.answer}\n, option_1: {self.option_1}\n, option_2: {self.option_2}\n, option_3: {self.option_3}"

classbook/staff/forms.py
from django.forms import ModelForm
from.models import Project, Question
from django import forms 
from django.core.exceptions import ValidationError 
 

class ProjectForm(ModelForm):
    template_name = "staff/form/form-template.html"
    class Meta:
        model = Project
        fields = '__all__'  # ukljuci sva polja
        # iskljuci 2 polja iz vida
        exclude = ['owner', 'num_of_likes', 'num_of_qustions', 'quiz_published']

 
class QuestionForm(ModelForm):
    template_name = "staff/form/question-form.html"

    class Meta:
        model = Question
        fields = '__all__'  # ukljuci sva polja
        # iskljuci 2 polja iz vida
        exclude = ['question_quiz']

 
    



 
    


 

classbook/staff/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Project, Question
from .forms import ProjectForm, QuestionForm
from django.db import IntegrityError
from .utils import is_connected, evaluate_project, get_all_project_names
from django.contrib.auth.decorators import login_required
from mysite.decorators import teacher_access_only
from django.http import JsonResponse
from django.core.files.storage import FileSystemStorage
import json 
from django.core.paginator import Paginator
 
@login_required(login_url="login")
@teacher_access_only()
def projects(request, *args, **kwargs):
    user = request.user
    try:
        print("user", user)
        '''projekti iz db za onog ko je logiran'''
        projects = Project.objects.filter(owner=user)
        #return render(request, 'staff/projects.html', context) 
        message = request.session.get('message')
        if message != None:
            context = {'projects': projects, 
                    'message': message}
        else:
            context = {'projects': projects}
 
        request.session['message'] = None
        return render(request, 'staff/projects.html', context)
    except :
        return render(request,'error.html', {'problem': 'The server is unable to read the data!'})

# kreira object koji dobije preko forme 
@login_required(login_url="login")
@teacher_access_only()
def createProject(request):
    if request.method == 'POST':
        #evaluira request paket u utils.py
        errors, context = evaluate_project(request)
        # sa request.FILES kazemo da ce doci i neki fajlovi(images, pdf, ..) sa POST
        form = ProjectForm(request.POST, request.FILES)
        # dodamo u context i jos jedan clan
        context['project_form'] = form
        
        try:
            #form valid i u errors sve value = False
            if form.is_valid() and not any(errors.values()): 
                form_data = form.cleaned_data
                print('project_published, project_published', form_data.get('project_published'), request.POST.get('project_published'))
                obj = form.save(commit=False)
                obj.owner = request.user
                obj.save()
                all_objects = Project.objects.all().order_by("id").reverse()
                pk = all_objects[0].id
                project =  get_object_or_404(Project, pk=pk)
                # updejtujemo project_published
                if  request.POST.get('project_published') == 'on':
                    project.project_published = True
                    project.save()
                return redirect('staff:get-project', pk)# ide na funkciju getProject()
            return render(request, 'staff/create-project.html', context)
        except :
            request.session['message'] ='You have not created a project!'
            return render(request, 'staff/create-project.html', context)
    return render(request, 'staff/create-project.html' )

# vrati projekt i kreira Quiz prvi put kad se projekt lodira
@login_required(login_url="login")
@teacher_access_only()
def getProject(request, pk):
    print('U get-project')
    # kojeg zelimo update procitamo iz db
    project =  get_object_or_404(Project, pk=pk)
    context = {'project': project}
 
    request.session['message'] = None
    return render(request, 'staff/single-project.html', context)

# brise project
@login_required(login_url="login")
@teacher_access_only()
def delete_Project(request):
    if request.method == 'POST':
        jsonData = json.loads(request.body)
        print('u delete_Project, jsonData', jsonData)
        # Attempt to sign user in
        pk = int(jsonData.get("pk"))
        project =  get_object_or_404(Project, pk=pk)
        try:
            # izbrise pdf fajl ako postoji
            if project.pdf :
                file_to_delite = project.pdf
                fs = FileSystemStorage()
                file_path = fs.path(file_to_delite.name)
                fs.delete(file_path)
                project.pdf = ''
                project.save()
            #izbrise project
        
            project =  get_object_or_404(Project, pk=pk)
            project.delete()
           
            return JsonResponse({"success": "yes"})
        except:
            request.session['message'] ='Delete of project was not successful!'
            return JsonResponse({"success": "no"})
    else:
        return render(request,'error.html', {'problem': 'You are not allowed to visit this page!'})


@login_required(login_url="login")
@teacher_access_only()
def publish_unpublish_Project(request, pk):
    if request.method == 'POST':
        try:
            user = request.user
            # kojeg zelimo update procitamo iz db
            project =  get_object_or_404(Project, pk=pk)
            print("in publishProject, a project.published", project.project_published)
            if project.project_published is None or project.project_published is False:
                project.project_published = True    # published
                project.save()
                print("Project published :user, user.isteacher:", user, user.is_teacher)
                return JsonResponse({"success": "published"})
            elif project.project_published is True:
                project.project_published = False  # unpublished
                project.save()
                print("Project published :user, user.is_teacher:", user, user.is_teacher)
                return JsonResponse({"success": "unpublished"})
            return JsonResponse({"success": "no"})
        except:
            return render(request,'error.html', {'problem': 'The server is unable to read the data!'})
    else:
        return render(request,'error.html', {'problem': 'You are not allowed to visit this page!'})
    
 
@login_required(login_url="login")
@teacher_access_only()
def get_projectNames(request):
    if request.method == 'POST':
        
        jsonData = json.loads(request.body)
        print('u evaluate_projectName, jsonData', jsonData)
        # Attempt to sign user in
        pk = jsonData.get("pk")
         #kreira se project
        if pk == 0:
            project_names = get_all_project_names()
             #edituje se project
        else:
            project_names = get_all_project_names(pk)
            #print('get_projectNames, project_names:',project_names)
        return JsonResponse({"project_names": project_names})
    else:
        return render(request,'error.html', {'problem': 'You are not allowed to visit this page!'})
    

# change_pdf
@login_required(login_url="login")
@teacher_access_only()
def update_pdf_file(request, pk):
    print('pk', pk)
    # kojeg zelimo update procitamo iz db
    project =  get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        # jel mozda bez fajla request
        try:
            uploaded_file = request.FILES['pdf']
        except:
            print('update_pdf_file-prazan paket')
            context = {'project_pdf': project.pdf, 'message': 'You must choose a pdf file!!'}
            return render(request,'staff/update-pdf-file.html', context)
        print('update_pdf_file, uploaded_file', uploaded_file)
        # ako vec postoji pdf za projekt, izbrisemo postojeci sa servera
        if project.pdf :
            file_to_delite = project.pdf
            fs = FileSystemStorage()
            file_path = fs.path(file_to_delite.name)
            fs.delete(file_path)
            print('file delited')
            # updejtujemo project
            project.pdf = uploaded_file
            project.save()
        else:   # ne postoji pdf file za project
            project.pdf = uploaded_file
            project.save()
        return redirect('staff:get-project',pk)
    else:
        context = {'project_pdf': project.pdf}
        return render(request,'staff/update-pdf-file.html', context)


@login_required(login_url="login")
@teacher_access_only()
def delete_File(request):
    if request.method == 'POST':
        jsonData = json.loads(request.body)
        print('u delete_Project, jsonData', jsonData)
        # pk mora biti int
        pk = int(jsonData.get("pk"))
        try:
            project =  get_object_or_404(Project, pk=pk)
            file_to_delite = project.pdf
            fs = FileSystemStorage()
            file_path = fs.path(file_to_delite.name)
            fs.delete(file_path)
            print('file delited')
            # updejtujemo project
            project.pdf = ''
            project.save()
            request.session['message'] ='Delete of pdf file was successful!'
            return JsonResponse({"success": "yes"})
        except:
            request.session['message'] ='Delete of pdf file was successful!'
            return JsonResponse({"success": "no"})
    else:
        return render(request,'error.html', {'problem': 'You are not allowed to visit this page!'})
    
@login_required(login_url="login")
@teacher_access_only()
def update_ProjectField(request, pk):
    print('U update_ProjectField,request:', request)
    project =  get_object_or_404(Project, pk=pk)
    if request.method == 'POST':
        try:
            jsonData = json.loads(request.body) 
            print('U update_ProjectField, jsonData', jsonData)
            key_list = list(jsonData.keys())
            # ime za field, nprprojectName
            field_name = key_list[0]
            field_value = jsonData.get(key_list[0])
            print('key_list',key_list, key_list[0],jsonData.get(key_list[0]))
            # PROMJENIMO VRIJEDNOST U DB ZA VALUE
            if field_name == 'projectName':
                project.projectName = field_value
            elif field_name == 'description':
                project.description = field_value
            elif field_name == 'video':
                project.video = field_value
            project.save()
        except:
            return JsonResponse({"success": 'no'})
        return JsonResponse({"success": 'yes'})
    else:

classbook/staff/templates/staff/form/edit-description.html
<div class="mb-3" id="div_id_description">
    <label for="id_description" class="form-label">
        <strong>Description</strong> <span class="span-info"  >The number of characters in the
            description must be less
            than 500!</span>
    </label>
    <div class="input-group has-validation">
        <textarea class="form-control" id="id_description" name="description" cols="40" rows="6" maxlength="500" >
                {% if project.description %} {{project.description}} {% endif %}
            </textarea>
    </div>
 
    <div class="invalid-feedback-client" id="izbor_descriptio_alert" ></div>
</div>

<div class="col-auto">

    <button type="button" id="" class="btn btn-primary mb-3 create-update-project" onclick="update_projectField()">Update</button>
    <button type="reset" id="" class="btn btn-secondary mb-3 create-update-project" onclick="cancelSubmit()">Cancel</button>
</div>

classbook/staff/templates/staff/form/edit-pdf.html
<!--csrf Za POST asihrono-->
<div class="debugging" hidden>
    <p id="csrf">{% csrf_token %}</p>
</div>

<div class="">
    <label for="id_pdf" class="form-label">
        <strong>Pdf</strong> <span class="span-info">Your file must not be larger than 1 MB and
            the number of
            characters in the name must be less than 30!</span>
    </label>
    <br>
    {% if project_pdf %}
    <div id="current_pdf">
        You current pdf file: {{project_pdf}}
    </div>
    {% endif %}
    <input type="file" class="custom-file-input" id="id_pdf" name="pdf" accept="application/pdf">
    <label class="custom-file-label" for="id_pdf" id="pdf_label">Choose file...</label>

    <!--sa js evaluation-->
    <div class="invalid-feedback-client" id="izbor_fajla_alert"></div>
</div>


<div class="col-auto">

    <input type="submit"  class="btn btn-primary mb-3 create-update-project" name="forma" value="Submit">
    <button type="reset" id="cancel_id" class="btn btn-secondary mb-3 create-update-project"
        onclick="cancel()">Cancel</button>
    {% if project_pdf %}
    <button type="button" class="btn btn-warning mb-3 create-update-project" id="delite_file" onclick="deletePDF()">Delete current file</button>
    {% endif %}
</div>

classbook/staff/templates/staff/form/edit-projectName.html
<div class="mb-3" id="div_id_projectName">
    <label for="id_projectName" class="form-label"><strong>Project Name</strong> <em>*</em></label>
    <div class="input-group has-validation">
        <input type="text" class="form-control is-valid" name="projectName" id="id_projectName" maxlength="100"     
        {% if project.projectName %} value="{{project.projectName}}" {% endif %} required>
        <div class="invalid-feedback">
            You must enter a Project Name.
        </div>
    </div>
    <div class="invalid-feedback-client" id="izbor_projectName_alert" >
    </div>
</div>

<div class="col-auto">

    <button type="button" id="" class="btn btn-primary mb-3 create-update-project" onclick="update_projectField()">Update</button>
    <button type="reset" id="" class="btn btn-secondary mb-3 create-update-project" onclick="cancelSubmit()">Cancel</button>
</div>

classbook/staff/templates/staff/form/edit-question-form.html
 
<div id="set-qustions">
    <div class="mb-3 row">
      <label for="question" class="col-sm-1 col-form-label">Question:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="question" name="question" value="{{ question.question }}" required >
      </div>
      <div class="invalid-feedback-client" id="question_alert" ></div>
    </div>
    <div class="mb-3 row">
      <label for="answer" class="col-sm-1 col-form-label" >Answer:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="answer" name="answer" value="{{ question.answer }}" required>
      </div>
      <div class="invalid-feedback-client" id="answer_alert" ></div>
    </div>
    <div class="mb-3 row">
      <label for="option_1" class="col-sm-1 col-form-label">Option 1:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="option_1" name="option_1" value="{{ question.option_1 }}" required>
      </div>
      <div class="invalid-feedback-client" id="option_1_alert" ></div>
    </div>
    <div class="mb-3 row">
      <label for="option_2" class="col-sm-1 col-form-label">Option 2:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="option_2" name="option_2" value="{{ question.option_2 }}" required>
      </div>
      <div class="invalid-feedback-client" id="option_2_alert" ></div>
    </div>
    <div class="mb-3 row">
      <label for="option_3" class="col-sm-1 col-form-label">Option 3:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="option_3" name="option_3" value="{{ question.option_3 }}" required>
      </div>
    </div>
    <div class="invalid-feedback-client" id="option_3_alert" ></div>
  </div>
 

  

classbook/staff/templates/staff/form/edit-video.html
<div class=" ">
    <div class="mb3" id="div_id_video">
        <label for="id_video" class="form-label"> <strong>YouTube Video</strong>*
            <span class="span-info">Your video url must have the following form:
                'https://www.youtube.com/watch?' + 'v=' + 'videoID'</span>
        </label>

        <div class="input-group has-validation">
            <input type="url" name="video" class="form-control is-valid" id="id_video" maxlength="100" {% if project.video %}
                value="{{project.video}}" {% endif %} required>
            <div class="invalid-feedback">
                Please choose a YouTube url.
            </div>
        </div>
        <!--sa js evaluation-->
        <div class="invalid-feedback-client" id="izbor_videa_alert"></div>
    </div>
</div>

<div class="col-auto">

    <button type="button" id="" class="btn btn-primary mb-3 create-update-project"
        onclick="update_projectField()">Update</button>
    <button type="reset" id="" class="btn btn-secondary mb-3 create-update-project"
        onclick="cancelSubmit()">Cancel</button>
</div>

classbook/staff/templates/staff/form/project-form-template.html
<!--csrf Za POST asihrono-->
<div class="debugging" hidden>
  <p id="csrf">{% csrf_token %}</p>
</div>

<div class="mb-3" id="div_id_projectName">
  <label for="id_projectName" class="form-label"><strong>Project Name</strong> <em>*</em></label>
  <div class="input-group has-validation">
    <input type="text" class="form-control is-valid" name="projectName" id="id_projectName" maxlength="100" 
    {% if projectName %} value="{{projectName}}" {% endif %} required 
    placeholder="">
    
    <div class="invalid-feedback">
      You must enter a Project Name.
    </div>
  </div>
  {% if error_projectName %}
  <div id="error_projectName" class="invalid-server-feedback">
    Such a Project Name already exists.
  </div>
  {% endif %}
  {% if error_projectName_length %}
  <div id="error_projectName_length" class="invalid-server-feedback">
    Project Name can have a maximum of 100 characters.
  </div>
  {% endif %}
  <div class="invalid-feedback-client" id="izbor_projectName_alert" >
  </div>
</div>

<div class="mb-3" id="div_id_description">
  <label for="id_description" class="form-label">
    <strong>Description</strong>   
  </label>
  <div class="input-group has-validation">
    <textarea placeholder="The number of characters in the description must be less than 500!" class="form-control" id="id_description" name="description" cols="40" rows="6" maxlength="500">{% if description %} {{description}} {% endif %}</textarea>
    <div class="invalid-feedback">
      Your description has too many characters.
    </div>
  </div>
  {% if error_description %}
  <div id="error_description" class="invalid-server-feedback">
    Your description has too many characters.
  </div>
  {% endif %}
  <div class="invalid-feedback-client" id="izbor_descriptio_alert" ></div>
</div>

<div class="border border-info-subtle">
  <div class="mb3" id="div_id_video">
    <label for="id_video" class="form-label"> <strong>YouTube Video</strong>*
    </label>
  
    <div class="input-group has-validation">
      <input type="url" name="video" class="form-control is-valid" id="id_video" maxlength="100" {% if video %}
        value="{{video}}" {% endif %}  required placeholder="Your video url must have the following form:
        'https://www.youtube.com/watch?' + 'v=' + 'videoID'">
      <div class="invalid-feedback">
        Please choose a YouTube url.
      </div>
    </div>
    <!--sa js evaluation-->
    <div class="invalid-feedback-client" id="izbor_videa_alert" ></div>
  </div>
</div>

<div class="border border-info-subtle">
  <label for="id_pdf" class="form-label">
    <strong>Pdf</strong>  <span class="span-info"  >
      Your file must not be larger than 1 MB and the number of
      characters in the name must be less than 30!</span>
  </label>
  <br>
  {% if valid_pdf %}
  <div id="valid-pdf-info" >
    Your current pdf file: {{valid_pdf}}
  </div>
  {% endif %}
  <input type="file" class="custom-file-input" id="id_pdf" name="pdf" accept="application/pdf" placeholder="hdhd">
  <label class="custom-file-label" for="id_pdf" id="pdf_label">Choose file...</label>
  <div class="invalid-feedback">Example invalid custom file feedback</div>
  {% if error_pdf_maxSize or error_pdf_file_name_length or error_pdf_extension %}
  <div>
    Your invalid choice for pdf file: {{pdf}}
  </div>
  {% endif %}
  {% if error_pdf_maxSize %}
  <div id="error_pdf_maxSize" class="invalid-server-feedback">
    The maximum file size that can be uploaded is 1 MB.
  </div>
  {% endif %}
  {% if error_pdf_file_name_length %}
  <div id="error_pdf_file_name_length" class="invalid-server-feedback">
    Number of characters in the name must be less than 50!.
  </div>
  {% endif %}
  {% if error_pdf_extension %}
  <div id="error_pdf_extension" class="invalid-server-feedback">
    .pdf is only allowed extension.
  </div>
  {% endif %}

  <!--sa js evaluation-->
  <div class="invalid-feedback-client" id="izbor_fajla_alert"></div>
</div>
<div><button id="clear_file" onclick="sakri_clear_file_btn()">Clear file</button></div>

<div class="border border-info-subtle">
  <div class="col-12">
    <div class="form-check">
      <label class="form-check-label" for="id_published">
        <strong>Published</strong> 
      </label>
      <input class="form-check-input " type="checkbox" name="project_published" id="id_published" {% if project_published %}
          value="{{project_published}}" {% endif %} checked="{{project_published}}" aria-describedby="invalidCheck3Feedback">
      <div id="invalidCheck3Feedback" class="">
        <span class="span-info" > You can later publish your project and thus enable students to use it. Until then,
          ONLY YOU HAVE ACCESS TO YOUR PROJECT.</span>
      </div>
    </div>
  </div>
</div>

<div class="col-auto">

  <input type="submit" id="submit_id" class="btn btn-primary mb-3 create-update-project" name="forma" value="Submit">
  <button type="reset" id="cancel_id" class="btn btn-secondary mb-3 create-update-project" onclick="cancelSubmit()">Cancel</button>
</div>

classbook/staff/templates/staff/form/question-form.html
<div id="set-qustions">
    <div class="mb-3 row">
      <label for="question" class="col-sm-1 col-form-label">Question:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="question" name="question" required>
      </div>
      <div class="invalid-feedback-client" id="question_alert" ></div>
    </div>
    <div class="mb-3 row">
      <label for="answer" class="col-sm-1 col-form-label">Answer:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="answer" name="answer" required>
      </div>
      <div class="invalid-feedback-client" id="answer_alert" ></div>
    </div>
    <div class="mb-3 row">
      <label for="option_1" class="col-sm-1 col-form-label">Option 1:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="option_1" name="option_1" required>
      </div>
      <div class="invalid-feedback-client" id="option_1_alert" ></div>
    </div>
    <div class="mb-3 row">
      <label for="option_2" class="col-sm-1 col-form-label">Option 2:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="option_2" name="option_2" required>
      </div>
      <div class="invalid-feedback-client" id="option_2_alert" ></div>
    </div>
    <div class="mb-3 row">
      <label for="option_3" class="col-sm-1 col-form-label">Option 3:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" id="option_3" name="option_3" required>
      </div>
    </div>
    <div class="invalid-feedback-client" id="option_3_alert" ></div>
  </div>

  