classbook/class/urls.py
from django.urls import path
from . import views

app_name = "class"
 
urlpatterns = [
    path('projects/', views.all_projects, name='all-projects'),
    path('project_search_view/', views.project_search_view, name='project_search_view'),
    path('project/<int:pk>', views.single_project, name='current-project'),
    path("remove_like/<int:pk>", views.remove_like, name="remove-like"),
    path("add_like/<int:pk>", views.add_like, name="like-project"),
    path("all-project-comments/<int:pk>", views.all_Comments_of_Project, name="all-project-comments"),
    path("add-comment/<int:pk>", views.add_Comment, name="add-comment"),
    path("edit-comment/<int:pk>", views.edit_Comment, name="edit-comment"),
    path("delete-comment/<int:pk>", views.delete_Comment, name="delete-comment"),
    path('submissions/', views.get_Subissions, name='submissions'),
    path('submit-quiz/<int:pk>/', views.submit_Quiz, name='submit-quiz'),
]

classbook/classbook/urls.py
from django.contrib import admin
from django.urls import path, include

# ovo nam treba za image url-treba pristup do settings da 
# povezemo (settings.MEDIA_URL, i settings.MEDIA_ROOT sa static()
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mysite.urls")),
    path('staff/', include('staff.urls')),
    path('class/', include('class.urls')),
]

# pip install Pillow za slike
# url za images madia, koristimo static()  helping method
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classbook/mysite/urls.py
from django.urls import path

from . import views

app_name = "mysite"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register-student", views.register_student, name="register-student"),
    path("register-teacher", views.register_teacher, name="register-teacher"),
    path("register-student-teacher", views.register_student_teacher, name="register-student-teacher"),
    path('get-users', views.get_users_Names, name='get-users'),
    path('play-quiz/<int:pk>/', views.play_Quiz, name='play-quiz'),
    path('get-quiz/<int:pk>/', views.get_Quiz, name='get-quiz'),
     
]

classbook/mysite/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    is_teacher = models.BooleanField(default=False)
    is_student = models.BooleanField(default=False)
    

classbook/mysite/forms.py
from django import forms
 
 
from django.core.exceptions import ValidationError 
 

class UserForm(forms.Form):
    username = forms.CharField(max_length=100)
    email = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100)
    confirmation = forms.CharField(max_length=100)
    status = forms.CharField(max_length=7)

   

   

classbook/mysite/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from .models import User
from .decorators import anonymous_user_only, anonymous_user
from django.contrib.auth.decorators import login_required
from staff.models import Project, Question
from . forms import UserForm
from .utils import validate_data

@anonymous_user()
def index(request, *args, **kwargs):
    return render(request, "mysite/index.html")

#za logiranje
@anonymous_user_only()
def login_view(request):
    if request.method == "POST":
        # Attempt to sign user in
        username = request.POST.get("username")
        password = request.POST.get("password")
        #authentication
        user = authenticate(request, username=username, password=password)
        # Check if authentication successful
        if user is not None:
            login(request, user)
            print("user, user.is_staff:", user, user.is_teacher)
            if user.is_teacher == True:
                return redirect('staff:projects')   # ako je user teacher
            else:
                return redirect('class:all-projects')    # ako je user student
        else:    # ako je user nije dobro unio podatke za login
            return render(request,"mysite/login.html",{"message": "Invalid username and/or password.", "success": "no"})
    else:# GET
        return render(request, "mysite/login.html")

@login_required(login_url="login")
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("mysite:index"))

 
@anonymous_user_only()
def register_student_teacher(request):
    print('U register_student_teacher')
    if request.method == 'POST':
        userform = UserForm(request.POST)
        context = {}
        data = {}
        if userform.is_valid():
            for key, value in request.POST.items():
                # Remove Leading and Trailing Whitespace from Strings sa strip()  methodom
                data[key] = value.strip()
            err_message = validate_data(data)   # evaluira data
            
            if err_message != '':
                print('err_message',err_message)
                 # zdruzimo errors i data u context
                context = data
                context['message'] = err_message
                return render(request, "mysite/register.html", context)
            # mozemo sacuvati
            if data["status"] == 'student':
                user = User.objects.create_user(
                            username = data['username'],
                            is_student = True,
                            email=data['email'],
                            password=data['password']
                        )
                user.save()
                login(request, user)
                #rdiarect na student
                return redirect('class:all-projects')# ide na funkciju getProject()
            else:
                user = User.objects.create_user(
                            username = data['username'],
                            is_teacher = True,
                            email=data['email'],
                            password=data['password']
                        )
                user.save()
                login(request, user)
                return redirect('staff:projects')# ide na funkciju getProject()
    return render(request, "mysite/register.html")

@anonymous_user_only()
def register_student(request):
    context = {"status": "student"}
    return render(request, "mysite/register.html", context)

@anonymous_user_only()
def register_teacher(request):
    context = {"status": "teacher"}
    return render(request, "mysite/register.html", context)
    
@anonymous_user_only()
def get_users_Names(request):
    try:
        all_users_obj = User.objects.all().order_by("id").reverse()
        all_users = []
        for user in all_users_obj:
            #print('username',user.username)
            all_users.append(user.username)
        return JsonResponse({"all_users": all_users})
    except:
        return JsonResponse({"success": "no"})


@login_required(login_url="login")
def play_Quiz(request, pk):
    user = request.user
    try:
        project =  get_object_or_404(Project, id=pk)
    except:
        return render(request,'error.html', {'problem': 'Such a project does not exist.!'})
    if project.quiz_published == False and user.is_student == True:
        problem = 'There is no published quiz for ' + project.projectName + ' project..!'
        return render(request,'error.html', {'problem': problem})
    context = {'is_student': user.is_student}
    return render(request,'mysite/quiz/quiz.html', context)


@login_required(login_url="login")
def get_Quiz(request, pk):
    user = request.user
    try:
        project =  get_object_or_404(Project, id=pk)
    except:
        return render(request,'error.html', {'problem': 'Such a project does not exist.!'})
    # teacher moze samo igrati kviz ako kviz nije publiciran i postoji bar 1 pitanje
    if project.quiz_published == False and user.is_student == True :
        problem = 'There is no published quiz for ' + project.projectName + ' project..!'
        return render(request,'error.html', {'problem': problem})
    quiz = Question.objects.filter(question_quiz = project)
    # list to store pitanja
    quiz_dict = []  
    for q in quiz:
        dict = {}   # prazan dictionary
        opt_list = []   # option list za svako pitannje
        # napunimo dictionery sa key-value
        dict["question"] = q.question
        dict["answer"] = q.answer   # row[1]
        #len_row = len(q)   # duzina liste row
        # napunimo option list
        opt_list.append(q.option_1)
        opt_list.append(q.option_2)
        opt_list.append(q.option_3)
        dict["opt"] = opt_list
        # dodamo u quiz_dict array dict
        quiz_dict.append(dict)
        #print('dict', dict)
    return JsonResponse({'list_dict': quiz_dict})
     
 
         

classbook/mysite/templates/mysite/index.html
{% extends "base.html" %}

{% block content %}
 
<div class="mb-4 small text-center text-muted">
    <h2>Welcome to Classbook!</h2>
</div>

{% if not user.is_staff %}

<h5>You can <span><a href="{% url 'mysite:register-teacher' %}">Register as Teacher</a></span> or
    <span><a href="{% url 'mysite:register-student' %}">Register as Student</a></span> or <span><a
            href="{% url 'mysite:login' %}">Log In</a></span>.
</h5>
<h6>If you register and log in as a student, you can use the projects prepared by the teachers.
    If you register and log in as a teacher, you can easily create projects that are intended for learning.</h6>

{% endif %}
{% endblock content %}

classbook/mysite/templates/mysite/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="buttonHolder">
  <h2>Login</h2>
</div>


<h3 style="color: red;" class="message">{{message}}</h3>
<div class="border-info-subtle">
  <form class="login_form " method="POST" action="">
    {% csrf_token %}
    <div class="form-group  mb-3">
      <label for="id_username">Username</label>
      <input type="text" name="username" class="form-control" id="id_username" placeholder="Username" required>
       <!--sa js evaluation-->
    <div class="invalid-feedback-client" id="izbor_username"></div>
    </div>
    <div class="form-group  mb-3">
      <label for="id_password">Password</label>
      <input type="password" name="password" class="form-control" id="id_password" placeholder="Password" required>
      <div class="invalid-feedback-client" id="izbor_password"></div>
    </div>

    <div class="buttonHolder">
      <input class="btn btn-primary mt-2 mb-2 login_form create-update-project" id="submit_login" type="submit" value="Login">
      <input class="btn btn-secondary" type="button" value="Cancel" onclick="cancel_Registeer_Login()">
    </div>
  </form>
</div>

<div class="vec-registriran">
  <h6>Don't have an account?</h6>
  <a style="text-decoration: none;margin-right: 10px;" href="{% url 'mysite:register-student' %}">Register as Student</a>
  
  <a style="text-decoration: none;" href="{% url 'mysite:register-teacher' %}">Register as Teacher</a>
</div>


{% block js %}
<script src="{% static 'mysite/js/login.js' %}"></script>
{% endblock js %}
{% endblock content %}

classbook/mysite/templates/mysite/register.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!--csrf Za POST asihrono-->
<div class="debugging" hidden>
    <p id="csrf">{% csrf_token %}</p>
</div>
<div class="buttonHolder">
    <h2>Register as {{status}}</h2>
</div>


<h3 style="color: red;" class="message">{{message}}</h3>

<div class="border-info-subtle">
    <form class="register_form" method="POST" action="{% url 'mysite:register-student-teacher' %}">
        {% csrf_token %}
        {% include 'mysite/form/register-tamplate.html' %}
        <div class="buttonHolder">
            <input class="btn btn-primary" type="submit" value="Register" >
            <input class="btn btn-secondary" type="button" value="Cancel" onclick="cancel_Registeer_Login()">
        </div>

    </form>
</div>

<div class="vec-registriran">
    Already have an account? <a href="{% url 'mysite:login' %}">Log In here.</a>
</div>


{% block js %}
<script src="{% static 'mysite/js/register.js' %}"></script>
{% endblock js %}

{% endblock content%}