classbook/class/urls.py
from django.urls import path
from . import views

app_name = "class"
 
urlpatterns = [
    path('projects/', views.all_projects, name='all-projects'),
    path('project_search_view/', views.project_search_view, name='project_search_view'),
    path('project/<int:pk>', views.single_project, name='current-project'),
    path("remove_like/<int:pk>", views.remove_like, name="remove-like"),
    path("add_like/<int:pk>", views.add_like, name="like-project"),
    path("all-project-comments/<int:pk>", views.all_Comments_of_Project, name="all-project-comments"),
    path("add-comment/<int:pk>", views.add_Comment, name="add-comment"),
    path("edit-comment/<int:pk>", views.edit_Comment, name="edit-comment"),
    path("delete-comment/<int:pk>", views.delete_Comment, name="delete-comment"),
    path('submissions/', views.get_Subissions, name='submissions'),
    path('submit-quiz/<int:pk>/', views.submit_Quiz, name='submit-quiz'),
]

classbook/classbook/urls.py
from django.contrib import admin
from django.urls import path, include

# ovo nam treba za image url-treba pristup do settings da 
# povezemo (settings.MEDIA_URL, i settings.MEDIA_ROOT sa static()
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mysite.urls")),
    path('staff/', include('staff.urls')),
    path('class/', include('class.urls')),
]

# pip install Pillow za slike
# url za images madia, koristimo static()  helping method
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classbook/class/models.py
from django.db import models
from mysite.models import User
from staff.models import Project
# Create your models here.

    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_comments")
    content = models.TextField(blank=False, max_length=200)
    date_created = models.DateTimeField(auto_now_add=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="project_Comments")
    

    def __str__(self):
         return f"{self.user} ima komentar : {self.content} za project {self.project}"
    
class Submission(models.Model):
    submission_owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_submission")
    date_created = models.DateTimeField(auto_now_add=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name="project_Submission")
    points = models.IntegerField(default = 0)
    max_points = models.IntegerField(default = 0)

    def __str__(self):
        return f"{self.submission_owner} je predao kviz za project {self.project}, kojeg je kreirAO {self.project.owner} i osvoio {self.points} od mogucih {self.max_points}"

     

classbook/class/forms.py
from django import forms

class NewCommentForm(forms.Form):
     content = forms.CharField(label="New Post", max_length=140, widget=forms.Textarea(attrs={"rows":"1"}))

classbook/class/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, JsonResponse
from django.db.models import Q
from staff.models import Project, User, Like
from .models import  Comment, Submission
from django.contrib.auth.decorators import login_required
from .utils import is_connected
from mysite.decorators import student_access_only
from . import forms
from django.core.paginator import Paginator
import json
# user: meho, password: kuku

@login_required(login_url="login")
@student_access_only()
def all_projects(request):
    print("U class/projects")
    #projekti iz db za onog ko je logiran
    all_projects = Project.objects.all().order_by("id").reverse()
    paginator = Paginator(all_projects, 10)
    page_number = request.GET.get('page')
    posts_of_the_page = paginator.get_page(page_number)
    # napunimo listu ko_ti_se_svidza
 
    #print('PROJECTS: request.user.is_staff', projects, request.user.is_staff)
    context = {'projects': all_projects, 'posts_of_the_page': posts_of_the_page}
    return render(request, 'class/all_projects.html', context)


@login_required(login_url="login")
@student_access_only()
def single_project(request, pk):
    print("U class/project")
    projectObj = get_object_or_404(Project, pk=pk)
    #projectObj = Project.objects.get(id=pk)
    teacher = User.objects.get(pk=request.user.id)
    # nadzemo like za id, kojeg brisemo
    like = Like.objects.filter(user=teacher, project=projectObj)
    jel_ti_se_svidza = False
    # ako je broj lajkova 1 za ovaj projekt od ovog usera
    if like.count() != 0:
        jel_ti_se_svidza = True
    #likes = projectObj.tags.all()
    context = {'project': projectObj, 
                'jel_ti_se_svidza': jel_ti_se_svidza,
                'is_conected': is_connected(),
                }
    return render(request, 'class/current-project.html', context)

'''“Like” and “Unlike”: Users should be able to click a button or link on any post to toggle
whether or not they “like” that post'''
@login_required(login_url="login")
@student_access_only()
def remove_like(request, pk):
    project = Project.objects.get(id=pk)
    # updejtujemo brok lajkova
    broj_lajkova = project.num_of_likes
    project.num_of_likes = broj_lajkova - 1
    #updejtuje project
    project.save()
    student = User.objects.get(pk=request.user.id)
    # nadzemo like za id, kojeg brisemo
    like = Like.objects.filter(user=student, project=project)
    like.delete()
    return JsonResponse({"message": "sussesiful"})

@login_required(login_url="login")
@student_access_only()
def add_like(request, pk):
    project = Project.objects.get(id=pk)
      # updejtujemo brok lajkova
    broj_lajkova = project.num_of_likes
    project.num_of_likes = broj_lajkova + 1
    project.save()
    student = User.objects.get(pk=request.user.id)
    # kreiramo novi red(objekt)
    newLike = Like(user=student, project=project)
    newLike.save()  # sacuvamo novi like za post i user

    return JsonResponse({"message": "sussesiful"})

# za search polje
@login_required(login_url="login")
@student_access_only()
def project_search_view(request):
    #print(request.GET)
    query = request.GET.get('q')    #<input type="serch" name="q">
     
    if query is not None:
        # trazi kljucne rijeci i za projectName i description
        lookups = Q(projectName__icontains=query) | Q(description__icontains=query)
        qs = Project.objects.filter(lookups)  
        #print(projectObj.projectName)
    
    context = {
         'object_list': qs,
         'query': query
    }
    return render(request,'class/search.html',context=context)

@login_required(login_url="login")
@student_access_only()
def all_Comments_of_Project(request, pk):
    '''All Comments: The “All Comments link in the navigation bar should take
        the user to a page where they can see all posts from all users for this project, with the most recent posts first.'''
    print('all_Comments_of_Project')
    # lista commentara u db za projekt, sortirani od zadnjeg do prvog
    project = Project(pk=pk)
    allComments_of_project = Comment.objects.filter(project=project).all().order_by("id").reverse()
    
    # Paginator  koliko dugu listu hocemo da vidimo na monitoru
    paginator = Paginator(allComments_of_project, 10)
    page_number = request.GET.get('page')
    posts_of_the_page = paginator.get_page(page_number)
    # procitamo imali u session sta
    message = request.session.get('message')
    if message != None:
        context = {"allComments_of_project": allComments_of_project, 'project_id': project.id , 
                    'message': message, 'posts_of_the_page':posts_of_the_page}
    else:
        context = { "allComments_of_project": allComments_of_project, 'project_id': project.id,'posts_of_the_page':posts_of_the_page}
    # izbrisemo sessen
    request.session['message'] = None
    return render(request, "class/all-comments.html", context)

'''When a user clicks “Edit” for one of their own comment, the content of their comment
should be replaced with a textarea where the user can edit the content of their post.'''

@login_required(login_url="login")
@student_access_only()
def edit_Comment(requst, pk):
    print("U edit")
    if requst.method == "POST":
        try:
            data = json.loads(requst.body)
            #print("data", data)
            # dobijemo red za id = post_id iz Post tabele
            edit_comment = Comment.objects.get(id=pk)
            edit_comment.content = data['content'].strip()
            # ako je duzina komentarapreduga
            if len(edit_comment.content) > 200:
                return JsonResponse({"susses": "no"})
            else:
                # sacuvamo promjenu kolone u db
                edit_comment.save()
                return JsonResponse({"susses": "yes"})
        except:
            return JsonResponse({"susses": "no"})
        
@login_required(login_url="login")
@student_access_only()       
def add_Comment(request, pk):
    print("U comment post")
    # ako je POST sacuva post
    if request.method == "POST":
        #print('request.POST["content"]',request.POST["content"])
        #print('Project.objects.get(id = pk)',Project.objects.get(id = pk))
        
        try:
            content = request.POST["content"]
            user = request.user
            project = Project.objects.get(id = pk)
            new_comment = Comment(content=content, user=user, project=project)
            new_comment.save()
            #return JsonResponse({"sussesiful": "yes" })
            return redirect('class:all-project-comments', pk = pk)
             
        except:
           return render(request,'error.html', {'problem': 'The comment was not successfully saved on the server!'})

@login_required(login_url="login")
@student_access_only()
def delete_Comment(request, pk):
    try:
        comment =  get_object_or_404(Comment, id=pk)
        comment.delete()
        return JsonResponse({"success": "yes"})
    except:
        request.session['message'] ='Delete of comment was not successful!'
        return JsonResponse({"success": "no"})

# funkcija za predaju rezultata kviza
@login_required(login_url="login")
@student_access_only()
def submit_Quiz(request, pk):
    if request.method == 'POST':
        try:
            project =  get_object_or_404(Project, id=pk)
        except:
            return JsonResponse({"message": "No such project", "success": "no"})
        if project.quiz_published == False:
            return JsonResponse({"message": "No quiz for project", "success": "no"})
        jsonData = json.loads(request.body)
        score = jsonData.get('score')
        max_score = jsonData.get('max_score')
        submission = Submission(submission_owner=request.user, project=project, points=score, max_points=max_score)
        try:
            submission.save()
        except:
            return JsonResponse({"message": "", "success": "no"})
        #print('score, max_score', score, max_score)
        return JsonResponse({"message": "", "success": "yes"})
    
@login_required(login_url="login")
@student_access_only()  
def get_Subissions(request):
    user = request.user
    all_submissions = Submission.objects.filter(submission_owner=user).all()
    #print('all_submissions', all_submissions)
    context = {'submissions': all_submissions,'name': user}
    return render(request, "class/submissions.html", context)
    

classbook/class/templates/class/all-comments.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<div class="text-end">
  <button class="btn-display-hide" id="go-home-comments" type="button" value=""  onclick="go_to_Project()">Go to Project</button>
</div>

<div id="message_div">
  {% if message %}
  <div class="alert alert-dismissible fade show {% if message %}{{ message }}{% else %}alert-primary{% endif %}"
    role="alert">
    <p style="color: brown;">{{message}}</p>
    <button type="button" id="alert_btn" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
  {% endif %}
</div>

<h3>All Comments</h3>
<div id="comment-post-div">
  <form id="form" method="POST" action="{% url 'class:add-comment' project_id %}">
    {% csrf_token %}

    <div class="">
      <textarea class="form-control" id="comment_textarea" rows="1" name="content" maxlength="200"
        placeholder="Write a Comment"></textarea>
      <div class="invalid-feedback-client" id="comment_alert"></div>
      <button type="submit" class="btn-clipboard form-disable" id="post_btn" data-bs-original-title="">Submit
        Comment</button>
    </div>
  </form>
</div>
<hr>
 
<div class="all-posts">
  {% for comment in posts_of_the_page %}
  <div class="comment-div mx-1" id="comment-div-{{comment.id}}">
    <!--Users should be able to click an “Edit” button or link on any of their own posts to edit that post.-->
    <div id="user-name">{{ comment.user.username }} </div>
    <div class="content" id="content_{{ comment.id }}">
      {{ comment.content}}
    </div>
    <div>
      {% if user.username == comment.user.username %}
      <!-- Button trigger modal edit-->
      <button type="button" class="btn-clipboard" id="edit-comment-btn" data-bs-toggle="modal"
        data-bs-target="#modal_edit_post_{{ comment.id }}">
        Edit comment
      </button>
      <!-- Button trigger modal delete -->
      <button type="button" class="btn-clipboard delete-button" data-bs-toggle="modal"
        data-bs-target="#modal_delete_post_{{ comment.id }}">
        Delete comment
      </button>
      <!-- Modal za delite-->

      <div class="modal fade" id="modal_delete_post_{{ comment.id }}" tabindex="-1" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p id="modal-body-question">Do you really want to delete the comment?</p> 
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-danger" value="{{comment.id}}" id="{{project_id}}"
                onclick="delete_Comment(value, id)">Delete comment</button>
            </div>
          </div>
        </div>
      </div>
      <!-- Modal za edit-->
      <div class="modal fade" id="modal_edit_post_{{ comment.id }}" data-bs-backdrop="static" data-bs-keyboard="false"
        tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="staticBackdropLabel">Edit Comment</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close" value="{{comment.id}}" onclick="correct_Value(value)"></button>
            </div>
            <div class="modal-body" id="modal-body-{{ comment.id }}">
              <textarea name="content" id="text-aria_{{ comment.id }}" cols="50"
                rows="3"> {{ comment.content }}</textarea>
                <div class="invalid-feedback-client" id="comment_alert_{{comment.id}}"></div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal" value="{{comment.id}}" onclick="correct_Value(value)">Close</button>
              <button type="button" class="btn btn-primary" value="{{comment.id}}"
                onclick="edit_Comment(value)">Save changes</button>
            </div>
          </div>
        </div>
      </div>
      {% endif %}
    </div>

  </div>
  {% empty %}
  <div class="alert alert-warning" role="alert">
    <h6>There is no comments!!!</h6>
  </div>
  {% endfor %}
</div>
<nav aria-label="Page navigation example">
  <ul class="pagination d-flex justify-content-center">
    {% if posts_of_the_page.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{posts_of_the_page.previous_page_number}}">Previous</a></li>
    {% endif %}
    {% if posts_of_the_page.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{posts_of_the_page.next_page_number}}">Next</a></li>
    {% endif %}
  </ul>
</nav>

{% block js %}
<script src="{% static 'class/js/all-comments.js' %}"></script>
<!--<script src="{% static 'network/likes_handeling.js' %}"></script>-->
{% endblock %}

{% endblock %}

classbook/class/templates/class/all_projects.html
{% extends "base.html" %}
{% load static %}


{% block content %}
<!--<img style="max-width: 200px; max-height: 200px;" src="{% static 'images/cat.jpg' %}" >-->
 
<h1>Projects:</h1>
 
{% if projects %}
 
<div class="box-class2">
  <div class="one"><h6>Project Title</h6></div>
  <div class="three">#Likes</div>
</div>

<div class="all-posts">
  {% for project in posts_of_the_page %}
 
  {% if project.project_published %}
  <div class="box-class2 project-div" >
    <div class="one"><a href="{% url 'class:current-project' project.id %}">{{project.projectName}}   </a></div>
    <div class="three">
      {{ project.num_of_likes }}

    </div>
  </div>
  {% endif %}
{% endfor %}
  {% else %}
  <div class="alert  alert-dismissible fade show {% if message.tags %}{{ message.tags }}{% else %}alert-primary{% endif %}" role="alert">  
    <h2>Project list is empty!!!</h2> 
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
{% endif %}
</div>

<nav aria-label="Page navigation example">
  <ul class="pagination d-flex justify-content-center">
    {% if posts_of_the_page.has_previous %}
    <li class="page-item"><a class="page-link" href="?page={{posts_of_the_page.previous_page_number}}">Previous</a></li>
    {% endif %}
    {% if posts_of_the_page.has_next %}
    <li class="page-item"><a class="page-link" href="?page={{posts_of_the_page.next_page_number}}">Next</a></li>
    {% endif %}
  </ul>
</nav>

{% block js %}  
    
{% endblock js %}

{% endblock content %}

classbook/class/templates/class/current-project.html
{% extends "base.html" %}
{% load static %}
{% load embed_video_tags %}

{% block content %}

<div class="text-end">
  {% if project.pdf %}
    <a href="{{project.pdfURL}}" target="_blank">See PDF File</a>
  {% endif %}
  {% if project.quiz_published %}
    <button class="btn-display-hide" id="" type="button" onclick="playQuiz()">Play <span id="quiz-samp">Quiz</span> </button>
  {% endif %}
  <!--<button class="btn-display-hide" id="" type="button" onclick="goHome()">Go Home</button>-->
  <button class="btn-display-hide" id="add-see-question" type="button" onclick="createQuestion()">Add/See/Edit Comments</button>
</div>

<!--poruka o updejtovanju-->
{% if message %}
<div class="alert alert-dismissible fade show {% if message %}{{ message }}{% else %}alert-primary{% endif %}"
  role="alert">
  <p info-alert>{{message}}</p>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}
<!-- The project tags: -->
<div id="project_div" class="">
  <div class="box-class2 mt-3">
    <div class="one">
      <h3>{{project.projectName}}</h3>
    </div>

    <div class="three">
      {% if jel_ti_se_svidza %}
      <button class="btn liked" style="color: red;" id="{{project.id}}" value="{{project.num_of_likes}}"
        onclick="likeHandler(id)"><i class="fa fa-heart"></i></button>
      <span id="br_lajkova_{{project.id}}">{{ project.num_of_likes }}</span>
      {% else %}<!--Isti, id za span i btn je isi  imamo jer se samo jedan pojavi-->
      <button class="btn not-liked" style="color: black;" id="{{project.id}}" value="{{project.num_of_likes}}"
        onclick="likeHandler(id)"><i class="fa fa-heart"></i></button>
      <span id="br_lajkova_{{project.id}}">{{ project.num_of_likes }}</span>
      {% endif %}
    </div>
  </div>

  <div class="project-edit">
    {% if project.description %}
    <p>{{project.description}} </p>
    {% endif %}
  </div>

 

  <div class="project-edit">
    <!--{% if request.is_secure %}HTTPS{% else %}HTTP{% endif %}-->
    {% video project.video as my_video %}
    {{project.video.url}}
    {% video my_video "medium" %}
    {% endvideo %}
  </div>


</div>

<hr>

{% block js %}
<script src="{% static 'class/js/current-project.js' %}"></script>
{% endblock js %}
{% endblock content %}

classbook/class/templates/class/search.html
{% extends "base.html" %}
{% load static %}


{% block content %}
 
<ol>
    {% for object in object_list %}
        {% if object.projectName %}
        <li>
            <a href="{% url 'class:current-project' object.id %}">
                {{ object.projectName }}</a>
        </li>
        
        {% endif %}
        {% empty %}
        <h3>There is no result for '{{query}}' search!!</h3>
    {% endfor %}
    </ol>
{% endblock content %}

classbook/class/templates/class/submissions.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Your submissions
{% endblock %}

{% block content %}


{% if submissions %}
<div class="mb-5 small text-center text-muted">
    <h4 id="submission-info">{{ name }} , your submitted quizzes and the points are:</h4>
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Quiz</th>
            <th>Points</th>
            <th>Date of submission</th>
        </tr>
    </thead>
    {% for submission in submissions %}
    <tbody>
        <tr>
            <td> {{ submission.project.projectName }}</td>
            <td> {{ submission.points }} of {{ submission.max_points }}</td>
            <td> {{ submission.date_created }}</td>
        </tr>
    </tbody>
    {% endfor %}
</table>
{% else %}
<div class="mb-5 small text-center text-muted">
    <h4 id="submission-info">{{ name }} </h4>
</div>
<div class="alert  alert-dismissible fade show {% if message.tags %}{{ message.tags }}{% else %}alert-primary{% endif %}" role="alert">  
  <h2>Submission list is empty!!!</h2> 
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}
{% endblock %}