classbook/class/urls.py
from django.urls import path
from . import views

app_name = "class"
 
urlpatterns = [
    path('projects/', views.all_projects, name='all-projects'),
    path('project_search_view/', views.project_search_view, name='project_search_view'),
    path('project/<int:pk>', views.single_project, name='current-project'),
    path("remove_like/<int:pk>", views.remove_like, name="remove-like"),
    path("add_like/<int:pk>", views.add_like, name="like-project"),
    path("all-project-comments/<int:pk>", views.all_Comments_of_Project, name="all-project-comments"),
    path("add-comment/<int:pk>", views.add_Comment, name="add-comment"),
    path("edit-comment/<int:pk>", views.edit_Comment, name="edit-comment"),
    path("delete-comment/<int:pk>", views.delete_Comment, name="delete-comment"),
    path('submissions/', views.get_Subissions, name='submissions'),
    path('submit-quiz/<int:pk>/', views.submit_Quiz, name='submit-quiz'),
]

classbook/classbook/urls.py
from django.contrib import admin
from django.urls import path, include

# ovo nam treba za image url-treba pristup do settings da 
# povezemo (settings.MEDIA_URL, i settings.MEDIA_ROOT sa static()
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("mysite.urls")),
    path('staff/', include('staff.urls')),
    path('class/', include('class.urls')),
]

# pip install Pillow za slike
# url za images madia, koristimo static()  helping method
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classbook/mysite/urls.py
from django.urls import path

from . import views

app_name = "mysite"
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register-student", views.register_student, name="register-student"),
    path("register-teacher", views.register_teacher, name="register-teacher"),
    path("register-student-teacher", views.register_student_teacher, name="register-student-teacher"),
    path('get-users', views.get_users_Names, name='get-users'),
    path('play-quiz/<int:pk>/', views.play_Quiz, name='play-quiz'),
    path('get-quiz/<int:pk>/', views.get_Quiz, name='get-quiz'),
     
]

classbook/staff/urls.py
from django.urls import path
from . import views

app_name = "staff"
urlpatterns = [
    path('projects/', views.projects, name='projects'),
    path('create-project/', views.createProject, name='create-project'),
    path('get-project/<int:pk>/', views.getProject, name='get-project'),
    path('delete-project/', views.delete_Project, name='delete-project'),
    path('publish-unpublish-project/<int:pk>/', views.publish_unpublish_Project, name='publish-unpublish-project'),
    path('get-projectNames/', views.get_projectNames, name='get-projectNames'),
    path('update-project-field/<int:pk>/', views.update_ProjectField, name='update-project-field'),
    path('update-pdf-file/<int:pk>/', views.update_pdf_file, name='update-pdf-file'),
    path('delete-file/', views.delete_File, name='delete-file'),
    path('get-create-quiz-question/<int:pk>/', views.get_create_Quiz_Question, name='get-create-quiz-question'),
    path('create-add-question/<int:pk>/', views.create_add_Question, name='create-add-question'),
    path('edit-question/<int:pk1>/<int:pk2>/<int:pk3>/', views.edit_Question, name='edit-question'),
    path('delete-question/<int:pk1>/<int:pk2>/', views.delete_Question, name='delete-question'),
    path('publish-unpublish-quiz/<int:pk>/', views.publish_unpublish_Quiz, name='publish-unpublish-quiz'),
]

classbook/templates/base/css.html
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<link href="{% static 'styles/styles.css' %}" rel="stylesheet">

<link href="{% static 'mysite/css/mysite-styles.css' %}"   rel="stylesheet">
<link href="{% static 'mysite/css/quiz.css' %}"   rel="stylesheet">
<!--<link href="/static/css/styles.css" rel="stylesheet">-->
        <!-- FontAweome CDN Link for Icons -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
{% if request.user.is_student%}
<!--Za like ikone samo u class app-->
<!--<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">-->
<link rel="stylesheet" href="{% static 'class/styles/class-style.css' %}">
{% endif %}

{% if request.user.is_teacher%}
<link rel="stylesheet" href="{% static 'staff/styles/staff-style.css' %}">

{% endif %}

classbook/templates/base/footer.html
 
<footer class="mb-5 small text-center text-muted">
    &copy; Mehmed Kukavica, 2023
</footer>

classbook/templates/base/js.html
{% load static %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" 
integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

 

 

classbook/templates/base/messages.html
{% if messages %}
<div class="container-fluid">
    {% for message in messages %}
        <div class="alert  alert-dismissible fade show {% if message.tags %}{{ message.tags }}{% else %}alert-primary{% endif %}" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
</div>
{% endif %}

classbook/templates/base/navbar.html
<nav class="navbar navbar-dark navbar-expand-lg bg-cfe">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Classbook</a>
      <span>{{request.user.username}}</span>
      <button class="navbar-toggler" style="background-color: #007cae; " type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" 
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
       
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if request.user.is_anonymous %}

        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'mysite:login' %}">Log In</a>
        </li>
        
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'mysite:register-student' %}">Register as Student</a>
        </li>
        
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'mysite:register-teacher' %}">Register as Teacher</a>
        </li>
          {% elif request.user.is_teacher %}
 
          <li class="nav-item">
            <!--<a class="nav-link" href="{% url 'staff:create-project' %}">Add Project</a>-->
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'staff:create-project' %}">Create Project</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'staff:projects' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'mysite:logout' %}">Log Out</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'class:all-projects' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'class:submissions' %}">My Submissions</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{% url 'mysite:logout' %}">Log Out</a>
          </li>
    
          {% endif %}
        </ul>
        {% if request.user.is_authenticated and request.user.is_student %}
        <form  method="GET" action="{% url 'class:project_search_view' %}"  class="d-flex" role="search">
          <input name="q" class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-secondary" type="submit">Search</button>
        </form>
        {% endif %}
      </div>
    </div>
  </nav>
  